version: "3"

services:
  wallet:
    build: app
    image: ghcr.io/mfathi91/shared-wallet-telegram-bot:${VERSION}
    volumes:
      - ./volumes:${VOLUMES_DIRECTORY}

    # Pass the required env variables to the application code
    environment:
      - VOLUMES_DIRECTORY=${VOLUMES_DIRECTORY}
      - VERSION=${VERSION}