version: "3"

services:
  wallet:
    build: app
    image: ghcr.io/mfathi91/shared-wallet-telegram-bot
    volumes:
      - ./app:/usr/src/app
      - ./volumes:/volumes
    environment:
      - VOLUMES_DIRECTORY=/volumes