name: Build & Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the unit tests
        shell: bash
        run: |
          python -m unittest

      - name: Change the version in .env file
        shell: bash
        run: |
          sed -i 's/VERSION=.*/VERSION=${{ github.event.inputs.release_version }}/' .env

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release v${{ github.event.inputs.release_version }}.
          tagging_message: v${{ github.event.inputs.release_version }}