name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Build & Release"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PATH }}

      - name: Get the version
        shell: bash
        run: |
          source .env && echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ghcr.io/mfathi91/shared-wallet-telegram-bot:${{ env.IMAGE_VERSION }}